parameters:
  dv_essentials.grunt_asset_manifest_path: '%kernel.project_dir%/config/assets.json'

services:
  essentials.listener.command_exception:
    class: Druidvav\EssentialsBundle\EventListener\ConsoleErrorListener
    tags:
      - { name: kernel.event_listener, event: console.error }
  Druidvav\EssentialsBundle\Twig\Basic:
    calls:
      - [ setTranslator, [ "@translator" ] ]
      - [ setGruntAssetManifestPath, [ "%dv_essentials.grunt_asset_manifest_path%" ] ]
    tags: [ "twig.extension" ]
  Druidvav\EssentialsBundle\Twig\Currency:
    calls:
      - [ setTranslator, [ "@translator" ] ]
    tags: [ "twig.extension" ]
  Druidvav\EssentialsBundle\Twig\Autolink:
    tags: [ "twig.extension" ]
  Druidvav\EssentialsBundle\Twig\Bootstrap5FormExtension:
    tags: [ "twig.extension" ]
